/// <reference types="react" />
import { TStylesProps as TRNSStylesProps } from '../stylers/types';
import rnsUseStyle from '../stylers/use-style';
import RNSIcon, { TIconProps as TRNSIconProps } from './icon';
import { TImageProps as TRNSImageProps } from './image';
import { TImageBackgroundProps as TRNSImageBackgroundProps } from './image-background';
import { TSafeAreaViewProps as TRNSSafeAreaViewProps } from './safe-area-view';
import { TScrollViewProps as TRNSScrollViewProps } from './scroll-view';
import { TTextProps as TRNSTextProps } from './text';
import { TTextInputProps as TRNSTextInputProps } from './text-input';
import { TPressableProps as TRNSPressableProps, TTouchableHighlightProps as TRNSTouchableHighlightProps, TTouchableOpacityProps as TRNSTouchableOpacityProps } from './touchable';
import { TViewProps as TRNSViewProps } from './view';
export declare const Icon: typeof RNSIcon;
export declare const Image: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSImageProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const ImageBackground: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSImageBackgroundProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const Pressable: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSPressableProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const SafeAreaView: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSSafeAreaViewProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const ScrollView: <TScrollViewStyle extends string, TScrollViewStyleNamespace extends string, TScrollViewContentContainerStyle extends string, TScrollViewContentContainerStyleNamespace extends string>({ styleNamespace, styleNames, style, contentContainerStyleNamespace, contentContainerStyleNames, contentContainerStyle, ...props }: TRNSScrollViewProps<TScrollViewStyle, TScrollViewStyleNamespace, TScrollViewContentContainerStyle, TScrollViewContentContainerStyleNamespace>) => JSX.Element;
export declare const Text: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSTextProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const TextInput: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSTextInputProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const ThemeProvider: import("react").FC<import("../theme-context").TContext>;
export declare const TouchableHighlight: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSTouchableHighlightProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const TouchableOpacity: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSTouchableOpacityProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare const useStyle: typeof rnsUseStyle;
export declare const View: <TStyleName extends string, TStyleNamespace extends string>({ styleNamespace, styleNames, style, ...props }: TRNSViewProps<TStyleName, TStyleNamespace>) => JSX.Element;
export declare type TStylesProps<TStyleName extends string, TStyleNamespace extends string> = TRNSStylesProps<TStyleName, TStyleNamespace>;
export declare type TPressableProps<TStyleName extends string, TStyleNamespace extends string> = TRNSPressableProps<TStyleName, TStyleNamespace>;
export declare type TTouchableHighlightProps<TStyleName extends string, TStyleNamespace extends string> = TRNSTouchableHighlightProps<TStyleName, TStyleNamespace>;
export declare type TTouchableOpacityProps<TStyleName extends string, TStyleNamespace extends string> = TRNSTouchableOpacityProps<TStyleName, TStyleNamespace>;
export declare type TIconProps<TStyleName extends string, TStyleNamespace extends string> = TRNSIconProps<TStyleName, TStyleNamespace>;
export declare type TImageProps<TStyleName extends string, TStyleNamespace extends string> = TRNSImageProps<TStyleName, TStyleNamespace>;
export declare type TImageBackgroundProps<TStyleName extends string, TStyleNamespace extends string> = TRNSImageBackgroundProps<TStyleName, TStyleNamespace>;
export declare type TSafeAreaViewProps<TStyleName extends string, TStyleNamespace extends string> = TRNSSafeAreaViewProps<TStyleName, TStyleNamespace>;
export declare type TScrollViewProps<TScrollViewStyle extends string, TScrollViewStyleNamespace extends string, TScrollViewContentContainerStyle extends string, TScrollViewContentContainerStyleNamespace extends string> = TRNSScrollViewProps<TScrollViewStyle, TScrollViewStyleNamespace, TScrollViewContentContainerStyle, TScrollViewContentContainerStyleNamespace>;
export declare type TTextProps<TStyleName extends string, TStyleNamespace extends string> = TRNSTextProps<TStyleName, TStyleNamespace>;
export declare type TTextInputProps<TStyleName extends string, TStyleNamespace extends string> = TRNSTextInputProps<TStyleName, TStyleNamespace>;
export declare type TViewProps<TStyleName extends string, TStyleNamespace extends string> = TRNSViewProps<TStyleName, TStyleNamespace>;
