import rnsUseStyle from '../stylers/use-style';
import RNSThemeProvider from '../theme-provider';
import RNSIcon from './icon';
import RNSImage from './image';
import RNSImageBackground from './image-background';
import RNSKeyboardAvoidingView from './keyboard-avoiding-view';
import RNSSafeAreaView from './safe-area-view';
import RNSScrollView from './scroll-view';
import RNSText from './text';
import RNSTextInput from './text-input';
import { Pressable as RNSPressable, TouchableHighlight as RNSTouchableHighlight, TouchableOpacity as RNSTouchableOpacity, } from './touchable';
import RNSView from './view';
export var Icon = RNSIcon;
export var Image = RNSImage;
export var ImageBackground = RNSImageBackground;
export var Pressable = RNSPressable;
export var KeyboardAvoidingView = RNSKeyboardAvoidingView;
export var SafeAreaView = RNSSafeAreaView;
export var ScrollView = RNSScrollView;
export var Text = RNSText;
export var TextInput = RNSTextInput;
export var ThemeProvider = RNSThemeProvider;
export var TouchableHighlight = RNSTouchableHighlight;
export var TouchableOpacity = RNSTouchableOpacity;
export var useStyle = rnsUseStyle;
export var View = RNSView;
//# sourceMappingURL=index.js.map